- Omikron/Factfinder/Block/FF/Communication.php
- Omikron/Factfinder/Helper/Data.php
- Solves issue: getting sessionId with wrong length
- Description: getting correct sessionId (always 30 characters)
- Tested with Magento editions/versions: 2.1.4
- Tested with PHP versions: 7.0.27
> Add helper method to get correct sessionId

- Omikron/Factfinder/Block/FF/Communication.php
When using the most recent ff-web-components version you will see an error in the javascript console, if the `version` parameter is not present on `<ff-communication>`.
>  add 'version' as a required param 

- Omikron/Factfinder/Helper/Tracking.php
According to FACT Finder support, the _Tracking.ff_ endpoint expects the _count_ parameter to be an integer without decimals, otherwise the tracking will not work (see Omikron ticket number 11039666).
> fix count of cart tracking

- Omikron/Factfinder/Model/Export/Product.php
No backend url in export csv column _ProductUrl_ anymore
The Extension loads data like store url for each product. For not visible products a backend url returns. The fix adds a filter to the collection that fetch all products. The collection contains only visible elements.
2.1.4
5.6.31
> filters collection for not visible products

- Omikron/Factfinder/Helper/Data.php
- Omikron/Factfinder/Model/Authentication/Password.php
- Omikron/Factfinder/etc/adminhtml/system.xml
- Solves issue: Password is not encrypted
- Tested with Magento editions/versions: 2.1.4
- Tested with PHP versions: 7.0.27
> Encrypt password

- Omikron/Factfinder/Controller/Adminhtml/Export/Feed.php
- Omikron/Factfinder/Controller/Adminhtml/TestConnection/TestConnection.php
- Solves issue: Fixes using $_SERVER global variable instead of embedded Magento 2 interfaces
- Tested with Magento editions/versions: 2.1.4
- Tested with PHP versions: 7.0.27
> Use magento referer variable

- Omikron/Factfinder/CustomerData/FF/Comumnication.php
- Omikron/Factfinder/etc/frontend/di.xml
Small typo in one of the last PRs.
> fix typo in "Communication" class name

- Omikron/Factfinder/CustomerData/FF/Communication.php
- Omikron/Factfinder/etc/frontend/sections.xml
- Omikron/Factfinder/view/frontend/templates/ff/communication.phtml
- Omikron/Factfinder/view/frontend/web/js/view/ffcommunication.js
#46 
download only attributes sid and uid via ajax instead of whole component
2.2.2+
5.6,7.1
> REWORKED/FFWEB-904: FF\Communication block disables FPC cache for a whole site

- Omikron/Factfinder/Helper/Product.php
Handle case when link to parent product exist but parent product itself doesn't exist
2.2.2+
5.6, 7.1
> BUGFIX/FFWEB-917 : Handle possible case when link to parent product exist but parent product itself doesn't.

- Omikron/Factfinder/Model/Export/Product.php
- Solves issue: Product URL and product image URL currently contain the domain of the default store, rather than the one from the actually processed store
- Description: By setting the store ID on the product object, the correct URL for the product URL and product image URL will be returned.
- Tested with Magento editions/versions: 2.2.6
- Tested with PHP versions: 7.1.13
> set store ID on product

- Omikron/Factfinder/view/frontend/web/js/search-redirect.js
Deleting of events properties "version" and "type" is now encapsulated into separate function
2.2.6
7.1
> Improve search-redirect.js readability

- CHANGELOG
- Omikron/Factfinder/Helper/Product.php
- Omikron/Factfinder/Test/Unit/Helper/ProductTest.php
Fix makes export correct configurable attribute values. If for instance attribute "manufacturer" was a select type, selected option identifier was exported, which was an integer value. Now, In this case it exports attribute option label (frontend value)
2.2.2+
7.1
> Bugfix/FFWEB-908 : Get correct configured attributes values depends on their type

- Omikron/Factfinder/Helper/Communication.php
The response from `Import.ff` might be the following:
```
{"error":"\u003cp\u003eIhnen fehlen die nötigen Rechte, um diese Seite zu bearbeiten. Bitte wenden Sie sich an Ihren Administrator.\u003c/p\u003e"}
```
This error would currently go unnoticed, because the `pushImport` function only checks for `errors` in the response, but not for a single `error`.
2.2.6
7.1.13
> check for 'error' in Import.ff response

- Omikron/Factfinder/view/frontend/layout/default.xml
The `header.panel` container might not be available in all themes, thus the important `<ff-communication>` block might not be inserted into the layout. The `after.body.start` position will always be present (as far as I know). There is no reason for the `<ff-communication>` element to be inside any actual DOM element. It should be one of the first elements on the page.
> move factfinder.communication to after.body.start

- Omikron/Factfinder/view/frontend/templates/ff/suggest.phtml
- Omikron/Factfinder/view/frontend/web/css/ff/suggest.css
- Solves issue:
#79  
Change `product-name`  CSS class to `ff-product-name` in order to differ from its origin Magento 2 class
2.2.6
7.1
> Github Issue #79: CSS classes/styles too genera

- Omikron/Factfinder/view/frontend/layout/factfinder_result_index.xml
Currently the `factfinder/result/index` route has no page title what soever, resulting in the following `<head>` tag:
```html
<title></title>
```
And of course the page title element within the content will not be there too.
> add missing page title

- Omikron/Factfinder/Helper/Data.php
- Omikron/Factfinder/Helper/Product.php
- Omikron/Factfinder/Model/Export/Product.php
- Omikron/Factfinder/etc/adminhtml/system.xml
- Omikron/Factfinder/etc/config.xml
This is a PR for #56.
Instead of exporting any additionally selected attributes in the `Attributes` column like so:
```
…|Bundesland=Niedersterreich|Produktmerkmal=bio|Produktmerkmal=vegan|…
```
every selected attribute gets its own column. So
```
ProductNumber;…;MagentoEntityId;Attributes
```
becomes
```
ProductNumber;…;MagentoEntityId;isbn_number;label_product;product_federal_state
```
Additionally, this PR also changes the regular expression of `cleanValue` to allow _any_ letter (including Umlauts etc., see #54).
This will obviously fundamentally change the export file and thus will require a reconfiguration of the fields in the FACT Finder channel.
> allow additional attributes to be direct export fields

- CHANGELOG
- Omikron/Factfinder/Block/FF/Communication.php
- Omikron/Factfinder/Helper/Data.php
- Omikron/Factfinder/etc/adminhtml/system.xml
Disable possibility to set 'keep-filters' param as it cause bug on Search requests with active filters with encoded special characters
2.2.6 +
7.1
> FFWEB-1007 : Remove 'keep-filter' parameter from module configuration

- Omikron/Factfinder/Model/Export/Product.php
In our case we do not want to filter the products by their visibility status. However, since the function is `private` we cannot easily extend and replace the class and this method.
> make getFilteredProductCollection function protected

- Omikron/Factfinder/view/frontend/templates/ff/campaign.phtml
Added <ff-campaign-redirect> in order to make redirect campaigns works
2.2.6
7.1
> FFWEB-1029 : Added<ff-campaign-redirect>

- Omikron/Factfinder/Model/Source/Attribute.php
- Omikron/Factfinder/Model/Source/FFVersion.php
- Omikron/Factfinder/etc/adminhtml/di.xml
- Omikron/Factfinder/etc/di.xml
- Solves issue: FFWEB-1047
- Description: In system configuration, all EAV attributes (incl. customer and category attributes) are available in the selectors. Only offer product attributes for the moment. 
- Tested with Magento editions/versions: 2.2.6, 2.3
> FFWEB-1047: Only make product attributes exportable

- Omikron/Factfinder/Helper/Product.php
In https://github.com/FACT-Finder-Web-Components/magento2-module/pull/84 I introduced a change to the `cleanValue` function, to allow any letter - including special characters like Umlauts. However, this currently breaks the encoding. e.g. 
```
Österreich
```
will be converted to
```
Ãsterreich
```
Adding the `u` pattern modifier to the regular expression (http://php.net/manual/en/reference.pcre.pattern.modifiers.php) fixes the issue.
However, this also means that only `utf-8` strings will be matched now ... anything else simply returns an empty string.
May be there is a better way to handle this?
2.2.7
7.1.26
> add u flag for preg_replace

- CHANGELOG.md
- src/Controller/Result/Index.php
- src/Model/Config/Source/Attribute.php
- src/Model/Export/BasicAuth.php
- src/etc/adminhtml/di.xml
- src/etc/adminhtml/system/data_transfer.xml
- Description: By accident in 1.0 we dropped the export attribute selection in the backend. This PR restores the previous status
- Tested with Magento editions/versions: 2.3
> Fix missing export attribute selection in backend

- CHANGELOG.md
- src/Observer/BaseTracking.php
- src/Observer/Tracking/AddToCart.php
- src/Observer/Tracking/Checkout.php
- src/Test/Unit/Observer/AddToCartTest.php
- src/Test/Unit/Observer/CheckoutTest.php
- src/etc/di.xml
- Solves issue:  
Silenced the responseException from FACT-Finder on Tracking when connection could not be established.
Disable tracking when FACT-Finder integration is disable
2.3.1
7.1
> FFWEB-1206 : Tracking Exceptions

- src/etc/crontab.xml
- src/etc/crontab/di.xml
#130
Fixes product export cronjob dependency injection issue.
Also adds a second (commented out) cronjob for CMS export.
The CMS export cronjob is commented out because there isn't
configuration for the system.xml yet and  I don't actually
know if the CMS cron functionallity is finished yet.
Magento Commerce 2.3.1
7.1
> Fixes product export cronjob dependency injection issue

- src/Model/Config/Communication/CacheConfig.php
- Solves issue: -
- Description: fixes "ERROR ff-communication: Boolean property [useCache] is expected be either true, false or empty, but is [1]. Falling back to false." error in the front end.
- Tested with Magento editions/versions: 2.2.8
- Tested with PHP versions: 7.1
> use getFlag method for use-cache

- src/view/frontend/templates/ff/asn.phtml
I think it would make sense to use translations in the `asn.phtml` template instead of the currently hard coded English labels.
> use translations in asn.phtml

- CHANGELOG.md
- phpcs.xml.dist
- src/view/frontend/web/js/search-navigation.js
#138 
Call setBaseUrl before building it prevent situations when baseUrl variable is null
2.2.8, 2.3.2
7.2
> FFWEB-1297: Added setBaseUrl before building it by URL utils

- CHANGELOG.md
- src/Model/Export/Catalog/ProductType/CompositeDataProvider.php
- src/Model/Export/Catalog/ProductType/SimpleDataProvider.php
- src/etc/di.xml
#124 
Added fix to price export for bundle and group products
2.3.0, 2.3.2
7.2
> FFWEB-1291: Price fix for bundle and group products

- CHANGELOG.md
- src/etc/adminhtml/system/cms.xml
- src/etc/adminhtml/system/data_transfer.xml
- Solves issue: #144
- Description: Add missing attribute in system.xml to allow empty multiselect fields
- Tested with Magento editions/versions: 2.3.2
> FFWEB-1314: Allow empty multiselect fields in system configuration

- CHANGELOG.md
- src/view/frontend/layout/catalog_product_view.xml
- src/view/frontend/layout/default.xml
- src/view/frontend/layout/factfinder_result_index.xml
- src/view/frontend/templates/ff/campaign-feedbacktext.phtml
- src/view/frontend/templates/ff/campaign-product.phtml
- src/view/frontend/templates/ff/campaign.phtml
- src/view/frontend/templates/ff/recommendation.phtml
- Solves issue: FFWEB-1353
- Description: Add missing product campaign on product detail page
- Tested with Magento editions/versions: 2.3.2
> FFWEB-1353: Product campaign on PDP

- src/Observer/CategoryView.php
- src/Test/Unit/Observer/CategoryViewTest.php
- Description: Add tests for layout load observer
- Tested with Magento editions/versions: 2.3.2
> FFWEB-1359: Add tests for layout load observer

- CHANGELOG.md
- src/Model/Api/Tracking.php
- Solves issue: FFWEB-1367
- Description: a `void` return target causes a fatal error in plugin target class. The issue is not present in M2 >= 2.3, but it can be easily solved for BC by removing the return type.
- Tested with Magento editions/versions: 2.2.5
> FFWEB-1367: Remove void return type from plugin target for BC

- src/view/frontend/templates/ff/communication.phtml
The current implementation of the `<ff-communication>` element causes the following HTML5 validation errors:
> Self-closing syntax (`/>`) used on a non-void HTML element. Ignoring the slash and treating as a start tag.
> End tag for `body` seen, but there were unclosed elements.
> Unclosed element `ff-communication`.
> do not use self-closing tag

- CHANGELOG.md
- phpcs.xml.dist
- src/Model/Api/Tracking.php
- src/Observer/Tracking/AddToCart.php
- src/Observer/Tracking/Checkout.php
- src/Test/Unit/Model/Api/TrackingTest.php
- src/Test/Unit/Observer/AddToCartTest.php
- src/Test/Unit/Observer/CheckoutTest.php
- Solves issue: FFWEB-1367
- Description: Remove variadic argument from method signature
- Tested with Magento editions/versions: CE 2.2.5
> FFWEB-1367: Ensure compatibility with Magento 2.2.x

- src/Model/Config/CommunicationConfig.php
- Solves issue: Server address is always taken from global configuration, not from store specific or website specific configuration
- Description: Added "stores" parameter to ScopeConfig::getValue()
- Tested with Magento editions/versions: 2.3.2 Commerce
- Tested with PHP versions: 7.1.26
> Fix server address not being retrieved from store specific configuration

- CHANGELOG.md
- src/Test/Unit/Model/Export/Cms/Field/ImageTest.php
- src/Test/Unit/Model/FieldRolesTest.php
- src/Test/Unit/ViewModel/CommunicationTest.php
- src/ViewModel/Communication.php
- src/view/frontend/templates/ff/communication.phtml
Connection parameters passed from config and from layout are now correctly merged
Previously communication parameters are merged using array + operator which makes the values from first array were taken and from second were ommited.  Right now parameters with string values are merged (separated by comma) and in case of boolean values, the value passed from layout is taken.  This could be observed while using custom 'add-params' values while navigating to category page
2.3.2
7.1
> FFWEB-1374 : Fix merge communication parameters

- src/Model/Export/Catalog/Products.php
Products which do not belong to a website are being indexed and thus show up in the search results with invalid links
This PR adds a filter for the current store to the product collection used for indexing
Magento Commerce 2.3.2
7.1.26
> Only add products to index which are active in current store.

- src/Console/Command/ExportProducts.php
- src/etc/di.xml
- Description: Adds a console command "factfinder:export:products" for exporting products to CSV file. This is especially useful during development, but maybe also for custom exporting strategies. You can define a store view too if you want.
- Tested with Magento editions/versions: 2.3.2 Commerce
- Tested with PHP versions: 7.1.26
> Add Console Command for exporting products

- src/Model/Export/Catalog/DataProvider.php
- src/etc/di.xml
- Description: When using custom product types, the export will break because a corresponding DataProvider is missing. Avoid errors by instantiating the SimpleDataProvider as a fallback instead
- Tested with Magento editions/versions: 2.3.2
> Provide fallback data provider for custom product types

- CHANGELOG.md
- src/view/frontend/web/js/search-navigation.js
- Solves issue: FFCSPV2-2070
- Description: A search request is accidentally triggered before redirecting a search to the search result page. This PR fixes this issue
- Tested with Magento editions/versions: 2.3.3
> Prevent search request before redirecting to result page

- CHANGELOG.md
- src/Model/Config/FeatureConfig.php
- src/Test/Unit/Model/Config/FeatureConfigTest.php
- Description: Even with FF disabled the layout switch on category pages would take place
- Tested with Magento editions/versions: 2.3
> Check current configuration before switching layout on category pages

- src/Controller/Adminhtml/TestConnection/TestConnection.php
- src/Test/Unit/Controller/Adminhtml/TestConnection/TestConnectionTest.php
- Description: When backend fields are disabled (e.g. prod mode when config is locked in the env.php) no POST data is sent for those values. Provide default values when this happens.
- Tested with Magento editions/versions: 2.3
- Tested with PHP versions: >=7.1
> Prevent errors during connection test when fields are disabled

- README.md
- src/Controller/Proxy/Call.php
- src/etc/frontend/di.xml
- src/view/frontend/templates/ff/communication.phtml
- src/view/frontend/web/js/view/ffcommunication.js
- Description:
Once user-id attribute is set, Web Components sends a request with login tracking. At the moment user id is set sever side by SessionData Parameter provider and also by additional script ffcommunication.js which download current user-id by ajax.
Both approaches are required since,  the block containing ff-communication component is  cached, and after returning to home page after logging in won't affect the ff-communication state (because of cache). So the ffcommunication.js bypassing that with its ajax call for user-id. However if user is redirected to dashboard after logging in, the communication won't be served from cache, but it will be rendered , now containing the user-id attribute. This cause login tracking is fired, and then the ffcommunication.js download the same …
> FFWEB-1411: Prevent login tracking duplication after customer landed on dashboard

- src/Model/StoreEmulation.php
- Solves issue: If you use the Magento translation function `__` in an exported field, translation didn't work if you started the export from the command line.
- Tested with Magento editions/versions: 2.3.3 Commerce
- Tested with PHP versions: 7.1.26
> Enable translations in store emulation

- CHANGELOG.md
- src/Controller/Proxy/Call.php
- src/Test/Integration/Controller/ProxyCallTest.php
- Description: Clicks on suggest items trigger a rest API call to the FF server. When the proxy function is active, the match pattern is too restrictive (.ff is expected, which is not the case for rest) and ends in a 404.
- Tested with Magento editions/versions: 2.3.3
> Extend proxy path match to include rest API calls

- CHANGELOG.md
- src/view/frontend/templates/ff/campaign-advisor.phtml
- Description: The presence of a name restricts the template to a given campaign. Remove the name to allow all campaigns to be displayed using the standard template.
- Tested with Magento editions/versions: 2.3.3
> Remove campaign name from default template

- CHANGELOG.md
- phpmd.xml.dist
- src/Controller/Proxy/Call.php
- src/Model/Http/ParameterUtils.php
- src/Test/Unit/Model/Http/ParameterUtilsTest.php
Fixed filterCategory was not encoded correctly for categories with at least two words i n name when using Proxy
2.3.2
7.1
> FFWEB-1528: Filtering categories fix

- CHANGELOG.md
- composer.json
- phpcs.xml.dist
- src/Test/Unit/ViewModel/CategoryPathTest.php
- src/ViewModel/CategoryPath.php
- src/view/frontend/templates/ff/recommendation.phtml
- Description: Magento performs no sorting when fetching parent categories from the category resource model. A manual sorting by level is added to render a correct path.
- Tested with Magento editions/versions: CE 2.3.2
> Enforce correct category path order in ViewModel

- CHANGELOG.md
- src/etc/view.xml
- Solves issue: FFWEB-1552
- Description: Prevent merging and/or bundling of all Web Components related files. Ideally we should add this to 1.4.2!
- Tested with Magento editions/versions: CE 2.3.2
> Prevent merging and bundling of Web Components

- src/Console/Command/ExportProducts.php
- src/Cron/Feed.php
- Description
Exporting feeds for multiple stores using store emulations cause default values will be fetched from config if no storeId argument will be passed
2.3.2
7.2
> FFCSPV2-2157: Pass store id while fetching channel name from store config

- src/Model/Export/Catalog/Entity/ProductVariation.php
- src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php
- src/Model/Export/Catalog/ProductType/SimpleDataProvider.php
Current implementation makes it hard for other modules to apply changes to the export. 
Depending on the project, data structures in magento might not match data structures for factfinder export. In many cases changing the export models is often the most cost-effective approach.
This PR improves the situation by introducing getters for product data and also making the parent configurable product data available to its simple contexts.
Eg. we had a use case where product images were only assigned to the configurable products.
With the upstream in this PR, it will be much more simple to do and changes in the shop less complex.
Magento Commerce 2.3.4
PHP 7.2
**Please note that the source …
> Improve extendability of product export

- CHANGELOG.md
- src/Model/Export/Catalog/Entity/ProductVariation.php
- src/view/frontend/web/js/search-navigation.js
- Solves issue: FFWEB-1579
- Description: Prevent slider filter requests from being redirected to search result page
- Tested with Magento editions/versions: CE 2.3.3
> FFWEB-1579: Prevent slider filter requests from being redirected

- src/ViewModel/CategoryPath.php
currently, when a category is saved with a trailing whitespace, it is trimmed during export but not when the categorypath is build for the frontend components. This leads to no records being found when a category has a trailing whitespace in the name
this pr just trims the category name that is used for the category path in f-communication
2.3.3
7.2
> trim category name when building category path

- CHANGELOG.md
- src/etc/adminhtml/system/data_transfer.xml
Added RECOMMENDATION push import type 
2.3.2
7.2
> FFWEB-1606: added RECOMMENDATION to available push import types

- README.md
- src/Model/Export/Catalog/ProductField/Attributes.php
- src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php
- src/Test/Unit/Model/Export/Catalog/ProductField/AttributesTest.php
- src/etc/adminhtml/system.xml
- src/etc/adminhtml/system/data_transfer.xml
- src/etc/adminhtml/system/feed.xml
- src/etc/di.xml
- Description: Currently we are exporting all additional attributes in a single field called Attributes. In order to improve and simplify the data configuration on FF, as suggested in the Optimized Feed guide, we should separate the Attributes in Filter- and SearchAttributes. **Important**: This could be a huge breaking change, we should consider a major version bump for it.
- Tested with Magento editions/versions: CE 2.3.3
> Attribute Export

- src/Model/Filter/TextFilter.php
- src/Test/Unit/Model/Filter/TextFilterTest.php
- Description: Improve export text filter by removing ALL non-printable characters
- Tested with Magento editions/versions: CE 2.3.4
> Filter non-printable characters in export feed

- README.md
- src/Model/Filter/TextFilter.php
- src/Test/Unit/Model/Filter/TextFilterTest.php
- Description: Currently, UFT-8 whitespace characters are not removed by the TextFilter, a test case is included.
- Tested with Magento editions/versions: CE 2.3.5
- Tested with PHP versions: PHP 7.2
> Remove UTF-8 whitespace with TextFilter

- .travis.yml
- src/etc/csp_whitelist.xml
- Closes #272  
- Description: Ensures compatibility with Magento 2.3.5, which introduced the CSP module
- Tested with Magento editions/versions: CE 2.3.5
- Tested with PHP versions: 7.2.25
> Magento CSP Compatibility

- src/ViewModel/CategoryPath.php
- Fixes #277 
- Description: When Varnish cache is active, a call including our `factfinder_categoy_view` handle is performed against the ESI controller on category pages, e.g. for the topnav. Since the category is not loaded, a call to the CategoryPath view model would fail. This whole part might be refactored in 2.x, so for the moment we can simply make the category optional.
> Make category optional in CategoryPath view model

- src/view/frontend/layout/factfinder_result_index.xml
- src/view/frontend/web/css/source/ff/_breadcrumb.less
- Closes #278 
- Description: Moving the searchbox to the content area makes project implementation more complicated, because often you might want the bar to stay in the header. Remove this feature from the module, like we do in other SDKs.
- Tested with PHP versions: 7.3
> Do no move searchbar to content

- CHANGELOG.md
- src/Observer/RedirectSearch.php
- src/Test/Unit/Observer/RedirectSearchTest.php
- Fixes #281
- Description: We are still referring to the legacy URL structure in the redirect observer, which is now deprecated.
- Tested with PHP versions: 7.4.9
> Fix redirect URL in controller_action_predispatch_* observer

- CHANGELOG.md
- src/view/frontend/layout/factfinder_category_view.xml
- src/view/frontend/templates/category/history_callback.phtml
- Solves issue: FFWEB-1855
- Description: Exclude category filter from URL on category pages
- Tested with PHP versions: 7.3
> FFWEB-1855: Exclude category filter from URL on category pages

- CHANGELOG.md
- src/Model/Export/Cms/Pages.php
- Closes: #289
Fixes filtering CMS pages when nothing is selected in blacklis
Ensures that pages assigned to all stores will be always include in export
2.3
7.2
> FFWEB-1899: CMS export fixes

- src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php
Using 
```php
Magento\ConfigurableProduct\Model\Product\Type\Configurable::getUsedProducts($product, $requiredAttributeIds = null)
```
instead of 
```php
Magento\ConfigurableProduct\Model\LinkManagement::getChildren($sku)
```
to avoid redundant operations executed on the configurable products children. LinkManagement in some moment use the
the `getUsedProducts` anyway.
2.4
7.4
> Improve ConfigurableDataProvider Performance

- src/Model/Export/Catalog/AttributeValuesExtractor.php
If there's no option selected for products select attribute, then `$product->getAttributeText($attributeCode)` returns empty array instead of empty string or `null`. Since we cast returned value to string, we are running into forbidden array to string conversion.
2.4
7.4
> FFWEB-2003: Prevent forbidden array to string conversion

- .github/workflows/ci.yml
- CHANGELOG.md
- src/Model/Export/Catalog/AttributeValuesExtractor.php
Solves issue:
If there's no option selected for products select attribute, then $product->getAttributeText($attributeCode) returns empty array instead of empty string or null. Since we cast returned value to string, we are running into forbidden array to string conversion.
Tested with Magento editions/versions:
2.4
Tested with PHP versions:
7.4
> FFWEB-2003 prevent forbidden array to string conversion

- CHANGELOG.md
- src/view/frontend/web/js/search-redirect.js
If user search for phrase containing special characters they will be not correctly formed during sending a request to FACT-Finder. This applies especially to shops using FACT-Finder 7.x version where `/` is used as a separator in category paths.
2.4
7.4
> FFWEB-20017: Encode event data before converting it to query parameter

- CHANGELOG.md
- src/view/frontend/web/js/view/ffcommunication.js
After user is logged in, reach page reloads causes Web Components to send a new login tracking request. This fix is preventing that.
2.4
7.4
> FFWEB-1892: Prevent sending redundant login tracking requests

- CHANGELOG.md
- src/Model/Export/Cms/Field/Image.php
- src/etc/di.xml
> FFWEB-2034: Fix "area code is not set" during installation on Magento2.4.2

- CHANGELOG.md
- src/Model/Export/Catalog/AttributeValuesExtractor.php
- src/Test/Unit/Model/Export/Catalog/AttributeValuesExtractorTest.php
Return and emtpy string if value is NULL while exporting attributes
- Description:
When AttributeValuesExtractor is exporting attributes, it should return an empty string instead of throwing errors when value is nullable
- Tested with Magento editions/versions: 2
- Tested with PHP versions:  7.4
> FFWEB-2062: Attribute export for products

- CHANGELOG.md
- README.md
- src/Model/Export/Catalog/Entity/ProductVariation.php
- src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php
- src/Test/Unit/Model/Export/Catalog/Entity/ProductVariationTest.php
- src/etc/di.xml
#321 
- Description:
Adds possibility to export fields stored on variants instead of copy values from configurable product
2.4
- Tested with PHP versions:
7.4
> FFWEB-2066: Add variant based field export

- CHANGELOG.md
- README.md
- src/Api/Export/FieldProviderInterface.php
- src/Model/Export/Catalog/Entity/ProductVariation.php
- src/Model/Export/Catalog/FieldProvider.php
- src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php
- src/Model/Export/FeedFactory.php
- src/Test/Unit/Model/Export/Catalog/Entity/ProductVariationTest.php
- src/etc/di.xml
Adds possibility to export fields stored on variants instead of copy values from configurable product
2.4
7.4
> FFWEB-2066: Add variant based field export V2
