FACT-Finder-Web-Components/magento2-module

Omikron/Factfinder/etc/config.xml

For more information see Ticket: FFWEB-318

set use_url_parameter to true as default

---

LICENSE
Omikron/Factfinder/Block/FF/RecordList.php

Fix Problem with setup:di:compile
Rearange the Parameters in annotations to resolve this issue.

Fix incompatible arguments type

---

Omikron/Factfinder/Controller/Router.php

- Solves issue: 100 router match iterations
- Tested with Magento editions/versions: 2.0.17, 2.1.4, 2.2.3
- Tested with PHP versions: 7.0.27

Fix router issue

---

Omikron/Factfinder/view/frontend/layout/catalog_product_view.xml
Omikron/Factfinder/view/frontend/layout/default.xml
Omikron/Factfinder/view/frontend/layout/factfinder_result_index.xml

This can avoid some issues with static content

Fix js and css naming in the layouts

---

Omikron/Factfinder/view/frontend/layout/factfinder_result_index.xml

follow up PR for #28. I missed the asn block.

add name to asn block

---

Omikron/Factfinder/Model/Export/Product.php

* Solves issue: 
#52 
* Description: 
Removes product limit on product export make larger than 50k product collection possible
Add product collection batching to prevent memory exhaustion on large product collection loading
* Tested with Magento editions/versions: 
2.2.2+
* Tested with PHP versions: 
5.6
7.1

BUGFIX/FFWEB-919 : Remove product limit on product export

---

Omikron/Factfinder/Helper/Product.php
Omikron/Factfinder/Model/Export/Product.php
Omikron/Factfinder/etc/adminhtml/system.xml
Omikron/Factfinder/etc/config.xml
Omikron/Factfinder/i18n/de_DE.csv

Allow user to choose visibility of exported products
2.2.2+
5.6, 7.1

FEATURE/FFWEB-914 : Allow user to choose visibility of exported products

---

Omikron/Factfinder/CustomerData/FF/Communication.php
Omikron/Factfinder/etc/frontend/sections.xml
Omikron/Factfinder/view/frontend/templates/ff/communication.phtml
Omikron/Factfinder/view/frontend/web/js/view/ffcommunication.js

Reverts FACT-Finder-Web-Components/magento2-module#58

Revert "REWORKED/FFWEB-904: FF\Communication block disables FPC cache for a whole site"

---

Omikron/Factfinder/Controller/Adminhtml/TestConnection/TestConnection.php
Omikron/Factfinder/Helper/Communication.php
Omikron/Factfinder/Helper/Data.php
Omikron/Factfinder/etc/adminhtml/system.xml
Omikron/Factfinder/view/adminhtml/templates/system/config/button/testconnection.phtml

Now You are able to test Your credentials without saving configuration

FEATURE/FFWEB-551: Test connection use form input data instead of saved configuration

---

CHANGELOG

Bugfix/FFWEB-973 : Prevents FOUC

---

Omikron/Factfinder/Block/FF/Communication.php

seo-prefix is of type string, not boolean

---

CHANGELOG

Update changelog file with changes for v0.9-beta.10 pre-release

Update changelog for version v0.9-beta.10

---

Omikron/Factfinder/Observer/Tracking/Checkout.php
Omikron/Factfinder/Test/Unit/Observer/AddToCartTest.php
Omikron/Factfinder/Test/Unit/Observer/CheckoutTest.php

Added unit tests to tracking observers
2.2.6
7.1

Added unit tests to tracking observers

---

src/view/adminhtml/templates/system/config/button/cms-feed.phtml

Merge Develop to Master

---

CHANGELOG.md
src/Cron/Feed.php

#135
Add Push Import on Cron feed export
2.2.8
7.1

FFWEB-1303: Add pushImport on Cron feed export

---

README.md

Added "Modification examples" chapter with two examples operation
- changing name of existing column
- adding new column

FFWEB-1313: Extend documentation

---

.travis.yml
README.md
composer.json
phpcs.xml.dist
src/Console/Command/ExportProducts.php
src/Model/Exporter.php

- Tested with Magento editions/versions: 2.3

Introduce Travis CI

---

src/view/frontend/templates/ff/suggest.phtml
src/view/frontend/web/css/source/ff/_suggest.less

Remove wrapping link tag in suggest which is parsed by bots

---

README.md
src/Model/Config/CommunicationConfig.php
src/etc/adminhtml/system/cms.xml
src/etc/adminhtml/system/general.xml
src/i18n/de_DE.csv

- Removed "Enrichment feature" in favour of "Proxy"
- Added note to "Adding new column" if CMS export is enabled
- Fixed Using FACT-Finder on category pages section

FFWEB-1565: Update documentation.

---

README.md

Add information about checkout tracking

---

README.md

Added troubleshooting section with first entry telling how to remove `pub/` fragment from the exported URLs

FFWEB-1724 add troubleshooting section

---

.travis.yml
src/etc/csp_whitelist.xml

- Solves issue: #267 
- Tested with PHP versions: 7.1, 7.2, 7.4

Magento CE v2.4 Compatibility

---

src/Api/Export/Catalog/ProductFieldInterface.php
src/Block/Adminhtml/System/Config/Field/ExportFields.php
src/Block/Adminhtml/System/Config/Field/Select.php
src/Console/Command/ExportProducts.php
src/Model/Config/ExportConfig.php
src/Model/Config/Source/Attribute.php
src/Model/Export/Catalog/AttributeValuesExtractor.php
src/Model/Export/Catalog/DataProvider.php
src/Model/Export/Catalog/Entity/ProductVariation.php
src/Model/Export/Catalog/ProductField/CategoryPath.php
src/Model/Export/Catalog/ProductField/FilterAttributes.php
src/Model/Export/Catalog/ProductField/GenericField.php
src/Model/Export/Catalog/ProductField/ProductImage.php
src/Model/Export/Catalog/ProductFieldProvider.php
src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php
src/Model/Export/Catalog/ProductType/SimpleDataProvider.php
src/Model/Export/Feed.php
src/Test/Unit/Model/Config/ExportConfigTest.php
src/Test/Unit/Model/Config/Source/AttributeTest.php
src/Test/Unit/Model/FieldRolesTest.php
src/etc/adminhtml/system.xml
src/etc/adminhtml/system/data_transfer.xml
src/etc/adminhtml/system/export.xml
src/etc/config.xml
src/etc/di.xml
src/view/frontend/templates/ff/record-list.phtml

- Solves issue: #260 
- Description: Redfine attribute export configuration and export values in multiattributes or single fields.
- Tested with Magento editions/versions: CE 2.3.5

Improve attribute export

---

CHANGELOG.md

Update readme for v1.6.3

---

CHANGELOG.md
src/view/frontend/templates/ff/similar.phtml

FFWEB-2043: add `idTtype` to `ff-similar products`

---

CHANGELOG.md
src/view/frontend/templates/ff/similar.phtml

FFWEB-2043: Add `idType` to `ff-similar-products`

---

README.md

Add new column to feed not working
After verifying issue I came to the conclusion that there was no error in the code, there was an error in the documentation
Magento 2
7.4

FFWEB-2085: Add new column to feed not working
